### ISSUE TITLE
Add possibility for recursive listing in MantaClient#ls()

### ISSUE THREAD

**Issue by ralphtheninja** [joyent/node-manta#106]
It would be nice if you could instruct [MantaClient#ls](https://github.com/joyent/node-manta/blob/master/lib/client.js#L817) to list all files and folders recursively.

**Comment by BobDickinson** [comment]
Super useful.  Is this documented anywhere?  I didn't see it here:

https://apidocs.joyent.com/manta/nodesdk.html
