### ISSUE TITLE
mls: TypeError: Cannot call method 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by rwsiv** [joyent/node-manta#154]
I'm running nodejs (v0.10.22) and node-manta (1.2.2) on Ubuntu 12.04 LTS.  I 'm finding that <code>mls ~~/</code> is failing with the error message:
<code>mls: TypeError: Cannot call method 'toUpperCase' of undefined</code>

About half the time, the command will run successfully.

I'm at a loss as why this occurring.  I have tried reinstalling nodejs and node-manta.

During the installation of node-manta, the following occurred:
<pre>> dtrace-provider@0.2.8 install /usr/lib/node_modules/manta/node_modules/watershed/node_modules/dtrace-provider
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.22"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/manta/node_modules/watershed/node_modules/dtrace-provider/.node-gyp"
gyp http GET http://nodejs.org/dist/v0.10.22/node-v0.10.22.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.22/node-v0.10.22.tar.gz
make: Entering directory `/usr/lib/node_modules/manta/node_modules/watershed/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory `/usr/lib/node_modules/manta/node_modules/watershed/node_modules/dtrace-provider/build'
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/debuglog/0.0.2
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/debuglog/0.0.2
npm http GET https://registry.npmjs.org/mv/0.0.5
npm http 304 https://registry.npmjs.org/mv/0.0.5

> dtrace-provider@0.2.8 install /usr/lib/node_modules/manta/node_modules/restify/node_modules/dtrace-provider
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.22"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/manta/node_modules/restify/node_modules/dtrace-provider/.node-gyp"
gyp http GET http://nodejs.org/dist/v0.10.22/node-v0.10.22.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.22/node-v0.10.22.tar.gz
make: Entering directory `/usr/lib/node_modules/manta/node_modules/restify/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory `/usr/lib/node_modules/manta/node_modules/restify/node_modules/dtrace-provider/build'

> dtrace-provider@0.2.8 install /usr/lib/node_modules/manta/node_modules/bunyan/node_modules/dtrace-provider
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.22"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/manta/node_modules/bunyan/node_modules/dtrace-provider/.node-gyp"
gyp http GET http://nodejs.org/dist/v0.10.22/node-v0.10.22.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.22/node-v0.10.22.tar.gz
make: Entering directory `/usr/lib/node_modules/manta/node_modules/bunyan/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory `/usr/lib/node_modules/manta/node_modules/bunyan/node_modules/dtrace-provider/build'</pre>

**Comment by davepacheco** [comment]
I ran into this and debugged it under #228.  Closing this one as a dup.
