### ISSUE TITLE
EPIPE on put

### ISSUE THREAD

**Issue by ekirkland** [joyent/node-manta#209]
Every once in a while I get the following exception out of the manta client put:

{"code":"EPIPE","errno":"EPIPE","syscall":"write"}

The file does not end up in manta, and I have engaged Joyent support to see if there are any related logs on their side, but we haven't been able to get to the bottom of it.  

Has anyone else experienced this?

**Comment by davepacheco** [comment]
Sorry we did not see this sooner.  I have not seen this behavior.  Is this support case still open?  Is there any more information about how you were invoking mput?

**Comment by ekirkland** [comment]
To be honest, I think we resolved it but I do not have the information anymore to provide more info.  Sorry about that.

I'll close this issue.
