### ISSUE TITLE
basic bash tab completion

### ISSUE THREAD

**Issue by davepacheco** [joyent/node-manta#214]
Initially requested by Yunong under internal ticket MANTA-705.

**Comment by trentm** [comment]
I ahve some *notes* (vapour right now) on adding support for bash completion file generation for dashdash and cmdln here: https://github.com/trentm/node-cmdln/blob/master/TODO.txt#L8-L18

**Comment by trentm** [comment]
Opinions welcome: 
How would you suggest getting a user of node-manta to install bash completion files for all the (dozen or so) `m*` tools?  For `triton` (a single command), users are pointed to instructions like these:

Installation (Mac):
    triton completion > /usr/local/etc/bash_completion.d/triton \
        && source /usr/local/etc/bash_completion.d/triton

Installation (Linux):
    sudo triton completion > /etc/bash_completion.d/triton \
        && source /etc/bash_completion.d/triton


However having the user do the equivalent of that for all the `m*` tools is obviously a non-starter.

Some ideas:

1. Have a "install-me-some-node-manta-bash-completions.sh" script (obviously not
   literally that name) that is part of the node-manta install, but not on the
   path by default. This would attempt find an appropriate "bash_completion.d"
   directory (it varies) and write "{mls,mget,...}.completion" there.
2. Perhaps have a npm post-install script that runs that script. Note that one
   of the issues is that sudo access might be needed to write to the
   "bash_completion.d" dir.
3. Have a new `mcompletion` tool that *is* on the PATH that one can use to
   install completions. I think this pollutes the PATH a little bit.
4. Have a new `msetup` tool that can install bash completions. This tool would
   (eventually) be a little more general than `mcompletion` in that it could
   help a user walk through setup of an account and `MANTA_*` envvars.

**Comment by trentm** [comment]
I've updated the title to be "basic" bash completion. I'll open a separate ticket for more advanced completion: specifically completing Manta dirs and paths (e.g. `mls ~~/stor/foo<TAB>`).

CR for this ticket: https://cr.joyent.us/#/c/943/

**Comment by trentm** [comment]
Added https://github.com/joyent/node-manta/issues/289 for improved bash completion work.

**Comment by trentm** [comment]
This is in manta@4.1.0 now
