### ISSUE TITLE
release v1.4.7

### ISSUE THREAD

**Issue by davepacheco** [joyent/node-manta#217]
Release v1.4.7 for #216.

**Comment by davepacheco** [comment]
I've tested "make prepush" with each of:

- 32-bit node v0.10.36 on illumos (SmartOS, joyent_20150127T213517Z)
- 64-bit node v0.12.0 on illumos
- 64-bit node v0.10.28 on OS X (10.8.5)
- 64-bit node v0.12.0 on OS X

All are clean.

**Comment by pfmooney** [comment]
The above test also ran clean on:
* 64-bit node v0.10.36 on Linux
* 64-bit node v0.12.0 on Linux
