### ISSUE TITLE
Installation errors under node v0.12.2

### ISSUE THREAD

**Issue by pborenstein** [joyent/node-manta#225]
Environment: OS X 10.10.3
$ xcodebuild -version
Xcode 6.3
Build version 6D570

When installing manta under node 0.12.2 (npm 2.7.5), I get a bunch of errors related to `dtrace_providers.cc`. Here's the log of the installation: https://gist.github.com/pborenstein/9e0ef7c4e117aad4fb81#file-installing-under-node-0-12-2

Here's the installation log under node 0.10.38 (npm 1.4.28): https://gist.github.com/pborenstein/9e0ef7c4e117aad4fb81#file-installing-under-node-0-10-38

**Comment by davepacheco** [comment]
Yeah, this is unfortunate.  manta needs to be updated to a newer dtrace-provider.  There were some rumors of memory leaks with either bunyan or dtrace-provider on newer versions, but I don't know what those were.

That said, the installation does complete successfully and seems to work (but presumably has no support for "bunyan -p").

**Comment by jbellenger** [comment]
I see the same errors when installing with node 4.2.2

**Comment by bahamat** [comment]
Help with running through #245 could land a fix for this sooner.

**Comment by chorrell** [comment]
I think we can close this out now that manta v3.0.0 is available:

https://github.com/joyent/node-manta/commit/f33f81ce237c25c8fe984f038a62bc3274b72ec8
