### ISSUE TITLE
mlogin resists request-level debugging

### ISSUE THREAD

**Issue by davepacheco** [joyent/node-manta#230]
I'm debugging an issue where account subusers can't use mlogin.  I get:

```
$ mlogin
 * created interactive job -- a47842b6-a5e2-e56b-acc2-e4e5d4c84a53
 * ERROR: Server did not Upgrade: ForbiddenError: 
 * cleaning up resources...
```

(The error is not part of this ticket.)  To debug that, I want the request id, so I use "-v", but that spews the logs to stderr.  If I redirect everything to bunyan, mlogin bails out early:

```
dap@b44c74d6 ~ $ mlogin -v 2>&1 | bunyan
 * ERROR: stdout is not a TTY; aborting.
```

Fair enough.  But even if I redirect only stderr, mlogin bails out early:

```
dap@b44c74d6 ~ $ mlogin -v 2>rqlog
dap@b44c74d6 ~ $ cat rqlog 
 * ERROR: stderr is not a TTY; aborting.
dap@b44c74d6 ~ $ 
```

This makes it hard to use "-v" to get request-level information.

**Comment by jclulow** [comment]
There is no particular reason for `mlogin` to use the `stderr` file descriptor for anything other than Bunyan logging.  Human-readable messages emitted as part of regular operation should really go to `stdout`, along with the rest of the terminal session.  Once we reserve `stderr` for Bunyan logs, one can do this:

```
 $ mlogin -v 2> >(bunyan -o short)
23:20:43.057Z DEBUG mlogin/MantaClient: createJob: entered (req_id=21be4af2-7698-4e54-b9ee-8d0f4a13b878, path=/example/jobs)
    job: {
      "name": "interactive compute job",
      "phases": [
        {
          "exec": "/assets/poseidon/public/medusa/agent.sh",
...
example@manta # exit
exit


 * remote process exited
 * cleaning up resources...
23:22:06.289Z DEBUG mlogin/MantaClient: unlink: entered (req_id=665f054e-a27f-42a5-ac79-8cf649cbd0d4, id=665f054e-a27f-42a5-ac79-8cf649cbd0d4, query={})
...
```
