### ISSUE TITLE
specifying a path multiple times to mfind results in crash

### ISSUE THREAD

**Issue by davepacheco** [joyent/node-manta#251]
```
$ mfind /dap/stor/drop /dap/stor/drop
mfind: AssertionError: operation "/dap/stor/drop" is already pending
```

The reason is that we use a vasync.barrier() to manage outstanding ftw operations for a single command-line argument, but vasync requires these to be unique.  We should probably dynamically construct a string here that includes the argument index as well as the path.

**Comment by bahamas10** [comment]
https://cr.joyent.us/4699
