### ISSUE TITLE
Update graceful-fs dep

### ISSUE THREAD

**Issue by BobDickinson** [joyent/node-manta#256]
Installing manta 2.0.7 on Node 5.8.0:

    npm WARN deprecated showdown@0.3.1: IMPORTANT hotfix
    npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

I looks like showdown is being addressed as part of #246.

Graceful needs some love also.

**Comment by trentm** [comment]
Fixed in #246.

```
$ npm install manta

> dtrace-provider@0.6.0 install /Users/trentm/tm/play/node_modules/dtrace-provider
> node scripts/install.js

play@1.0.0 /Users/trentm/tm/play
└── manta@3.0.0  extraneous

npm WARN play@1.0.0 No repository field.

$ node --version
v5.11.1
```
