### ISSUE TITLE
mput fails with "stream.listenerCount is not a function error" on freeBSD

### ISSUE THREAD

**Issue by feetwins** [joyent/node-manta#262]
**Initial problem:**

While most manta CLI commands work on freeBSD, the mput command returns with a consistent error:

`mput: TypeError: stream.listenerCount is not a function`

This seems to be isolated to the OS:

`root@40360b48-1bd3-42fa-b2c9-82ba33cae559:~ # uname -a
FreeBSD 40360b48-1bd3-42fa-b2c9-82ba33cae559 10.3-RELEASE FreeBSD 10.3-RELEASE #0 r297264: Fri Mar 25 02:10:02 UTC 2016 root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC amd64`

**Culprit identified as (courtesy of user that originally reported the problem):**

- node/lib/readline.js makes calls to stream.listenerCount, which is, as the error message suggests, a function not defined by the stream library.

- Manta calls readline from the progress bar drawing routine in the put function.

- Calls to mput from FreeBSD should therefore be called with the -q option until readline.js is fixed, such as follows:

`mput -q -f .shrc ~~/shrc`

**Comment by feetwins** [comment]
**Another workaround has been noted as such:**

Another workaround is to add modify the node-progbar library to include 'freebsd' in the list of platforms upon which to write directly to the TTY instead of using node's readline:

In the file manta/node_modules/progbar/lib/progbar.js there is a 
variable called UNIX_PLATFORMS that could be expanded to include 
'freebsd' (for now it only includes solaris and linux).

**Comment by davepacheco** [comment]
Thanks for this.  The suggested change would be to [node-progbar](https://github.com/jclulow/node-progbar).  It's still not clear why readline doesn't seem to work at all on Node 6 on BSD.

**Comment by jclulow** [comment]
I pushed a fix for the `listenerCount()` issue (see jclulow/node-progbar#17) and published `progbar@1.1.1`.  As the current `manta` module depends on a range version for `progbar`, reinstalling dependent modules should pull in `progbar@1.1.1` and the fix.
