### ISSUE TITLE
Add a  '-j,--json' option to `mfind` to get the raw JSON objects for each matched file. 

### ISSUE THREAD

**Issue by chorrell** [joyent/node-manta#266]
The use case is so that you can get the full properties of each found file. So for instance, the json of a matched fill with json output would include an 'mtime' field that you could use for doing further filtering based on date/time.

**Comment by davepacheco** [comment]
This was implemented under #265 a few weeks ago and part of version 3.1.0 (not yet published to npm, it looks like).
