### ISSUE TITLE
job expressions do not honor --memory

### ISSUE THREAD

**Issue by cburroughs** [joyent/node-manta#280]
```
$ cat /tmp/logs | mjob create --image=16.x.x --memory=2048 -o 'grep audit' ^^ 'wc -l'
added 2 inputs to 7f30f152-653a-c808-b0a4-81305438137a
1516
$ mjob get 7f30f152-653a-c808-b0a4-81305438137a
{
  "id": "7f30f152-653a-c808-b0a4-81305438137a",
  "name": "",
  "state": "done",
  "cancelled": false,
  "inputDone": true,
  "transient": false,
  "stats": {
    "errors": 0,
    "outputs": 1,
    "retries": 0,
    "tasks": 3,
    "tasksDone": 3
  },
  "timeCreated": "2016-11-02T14:34:44.351Z",
  "timeDone": "2016-11-02T14:34:57.421Z",
  "timeArchiveStarted": "2016-11-02T14:34:58.175Z",
  "timeArchiveDone": "2016-11-02T14:34:58.668Z",
  "phases": [
    {
      "exec": "grep audit",
      "image": "16.x.x",
      "type": "map"
    },
    {
      "exec": "wc -l",
      "image": "16.x.x",
      "type": "reduce"
    }
  ],
  "options": {}
}
$ head -5 .npm-packages/lib/node_modules/manta/CHANGES.md 
# node-manta Changelog

## not yet released

## 3.1.3
```

**Comment by cburroughs** [comment]
There are two different option parsing paths and they have different behaviors:
 * When using `-m` and `-r` options like `--image` apply  to the *next* phase.
 * When using job expressions (`^` `^^`) options apply to *all* phases, but not all options were handled.

**Comment by trentm** [comment]
@cburroughs Can you confirm the application of all of `--image`, `--disk` and `--memory` for each of those forms of defining the phases?  The current *docs* for `--disk` and `--memory` imply that it is for all phases... but the *processing* looks like it was going to apply disk/memory only for the next phase.

- we should have test cases for these
- I'd vote to deprecate and start removing the cutesy `^/^^` form from docs.

**Comment by trentm** [comment]
oh, there is https://cr.joyent.us/#/c/838/

**Comment by trentm** [comment]
^^^ The CR above will fix the immediate problem that '--disk,--memory,--init' are currently ignored for the 'mjob create' style using `^,^^`.

But what about the subtlety that `--memory 123` applies only to the next phase if using the `-m,-r` style, but applies to all phases if using the `^,^^` style? I can try to clarify the subtlety in the help output (as part of https://github.com/joyent/node-manta/issues/279). However:

@cburroughs @davepacheco  Thoughts on deprecating the `^,^^` style? I.e. *support* it, but explicitly mark it as deprecated and start taking examples of it out of the docs. Having both styles is just confusing (esp. when it other options are interpreted differently).

**Comment by cburroughs** [comment]
I think the cutesy style helps get across the "It's like Unix!" concept better than a bunch of repeated flags.  I'd suspect it might be *better* for the intro docs for that purpose.

I suspect that anyone using Manta for complicated repeated workloads is probably using one of the SDKs instead of shelling out to `mjob`, and that shelling out to `mjob` with custom init/assets/memory is probably uncommon.  So I think it's confusing, but because the ground is rarely trodden it doesn't trip many people up in practice.  If my suspicious are wrong and we do have other reports of it tripping people up than I agree it's confusing to have two ways and we should prefer the more explicit one.
