### ISSUE TITLE
~~ evaluation needs to be less pedantic

### ISSUE THREAD

**Issue by bahamat** [joyent/node-manta#293]
Performing operations on `~~` returns `InvalidPathError`, while using `~~/` evaluates to `/$MANTA_USER/`.

E.g., `mls ~~` fails, but `mls ~~/` works, yet both `mls /$MANTA_USER` and `mls /$MANTA_USER/` work.

**Comment by trentm** [comment]
https://cr.joyent.us/#/c/1091/

**Comment by KodyKantor** [comment]
Closing this. This has been integrated for a while.
```
➜  ~ mls --version
5.1.1
http://apidocs.joyent.com/manta
➜  ~ mls ~~
jobs/
public/
reports/
stor/
uploads/
```
