### ISSUE TITLE
Proposal: use a different test framework

### ISSUE THREAD

**Issue by geek** [joyent/node-manta#297]
Current issues:
1. When there is an issue in a test you get an unhelpful `FAILURES: Undone tests (or their setups/teardowns):`. 
1. Cannot run a range of tests
1. No code coverage reporting
1. No grouping of similar tests (no describe)

Proposal:
Move to lab or another compatible framework. I suggest lab because I maintain it and it has built-in code coverage support.

I am happy to migrate the tests over to lab, just let me know.

**Comment by trentm** [comment]
Wyatt,

Perhaps tape? We've a lot of repos using that and have generally been
moving to tape when selecting something other than nodeunit.
Agreed that nodeunit isn't serving us well.


$ cd ~/all-joy-repos    # actually just "many" of joyent's repos, not a
complete list
$ ls */package.json | wc -l
     102
$ grep nodeunit */package.json | wc -l
      31
$ grep tape */package.json | wc -l
      32


Trent

-- Trent

**Comment by davepacheco** [comment]
I use catest for my modules.

For what it's worth, you can run individual test files with nodeunit, but I don't think there's a way of running individual tests within files.

Would we have to rewrite all the tests to switch to lab or tape?  How would we verify that the tests still test the right things?

**Comment by pfmooney** [comment]
When I've converted other modules from nodeunit to tape, I don't believe too much rework was required on the tests themselves.  If the setup/teardown functionality in nodeunit was used, those portions needed to be converted into something that tape could handle.  (It doesn't have a "native" mechanism for that.)

**Comment by trentm** [comment]
@pfmooney Two of node-manta's test files have setUp and tearDown usage. For imgapi's and other repos' migration to tape I've just changed those to separate "test(...)" calls at the start and end of the file, which has worked fine.

**Comment by pfmooney** [comment]
@trentm Yeah, I've used a custom little tape pattern in other repos which required setup/teardown on a large number of tests.  The challenge of fixing that small aspect has always outweighed the problems of nodeunit.

**Comment by trentm** [comment]
I'm stealing this issue and replacing it with https://smartos.org/bugview/MANTA-4432  Sorry for the bug system change.
