### ISSUE TITLE
mfind should probably require at least one path argument

### ISSUE THREAD

**Issue by davepacheco** [joyent/node-manta#303]
If provided no path arguments, `mfind` searches `/$MANTA_USER/stor`.  I'm not sure how useful that is.  I don't think it's a common operation, and it's pretty confusing (and, in some cases, dangerous) when somebody was really doing `mfind $SOME_VAR` and `$SOME_VAR` turns out to be undefined.

Obviously, this is a breaking change.

**Comment by davepacheco** [comment]
Also of note, find(1) does require at least one path.

**Comment by jclulow** [comment]
This seems a reasonable breaking change to make.

**Comment by bahamas10** [comment]
This is already the case on the latest master, however it appears to be by chance.

```
# ./bin/mfind 
path required
usage: mfind [OPTIONS] path...
options:
// -snip
```

The error is generated here: https://github.com/joyent/node-manta/blob/1c9f45adbe8c0cbe82c487bb2c84a7b7fa1a5bcb/lib/options.js#L83-L85

However, there is logic currently in `mfind` that constructs the users `~~/stor` directory if no arguments are specified, so I've created this CR to 1. remove that and 2. assert that at least 1 path is specified before we loop the arguments.

https://cr.joyent.us/4700
