### ISSUE TITLE
node-manta affected by usdt cross-arch build bug

### ISSUE THREAD

**Issue by bahamat** [joyent/node-manta#336]
see chrisa/usdt#16

Fix is to update restify-clients to 1.5.2.

**Comment by davepacheco** [comment]
https://github.com/chrisa/libusdt/issues/16

**Comment by bahamat** [comment]
Both `make check` and `make test` pass from my workstation.

macOS 10.13.1
node.js v4.8.5

**Comment by bahamat** [comment]
This has all been one big red herring. Some investigation led me to create this issue, and on further investigation, this is not what was causing the issue I was seeing.

While updating deps is probably a good idea anyway, we don't want to do that in response to an invalid bug, so closing this.
