### ISSUE TITLE
documentation is out-of-date

### ISSUE THREAD

**Issue by bahamas10** [joyent/node-manta#355]
https://apidocs.joyent.com/manta/index.html#getting-started

see https://github.com/joyent/manta/blob/master/docs/user-guide/index.md#getting-started

**Comment by davepacheco** [comment]
Thanks for noting this.  I think this is a dup of [MANTA-3610](https://smartos.org/bugview/MANTA-3610), and I don't think any of those docs are in this repo, are they?

**Comment by bahamas10** [comment]
That's correct.  I meant to close out this issue but forget, thanks!
