### ISSUE TITLE
mfind limit documentation could be clearer

### ISSUE THREAD

**Issue by jimrybarski** [joyent/node-manta#359]
I wanted to test a pipeline on just 100 files, using mfind's `--limit` option, but the limit is ignored:
```
mfind --limit 100 ~~/stor/stats_data | mjob create -o 'gunzip' ^^ 'sort | uniq | gzip | mpipe ~~/stor/stats-output.gz'
added 1000 inputs to 01f97ee3-a8b7-691d-8b96-8cece158ebe2
added 1000 inputs to 01f97ee3-a8b7-691d-8b96-8cece158ebe2
added 1000 inputs to 01f97ee3-a8b7-691d-8b96-8cece158ebe2
```
This goes on - needless to say it's finding way more than the 100 files I expected.

```
mfind --version
5.2.1
```

**Comment by davepacheco** [comment]
The documentation is maybe not as clear as it should be, but I believe `--limit` refers to the number of entries retrieved with each HTTP request that `mfind` makes under the hood.  It's not intended to control the number of entries output by the command.
