### ISSUE TITLE
mfind hangs when piped into head

### ISSUE THREAD

**Issue by jimrybarski** [joyent/node-manta#360]
I can run the command below where I just want to save 100 filenames to my local computer:

`~~/stor/stats_data | head -n 100 > test-inputs.txt`

However, this will hang indefinitely. Curiously, the file `test-inputs.txt` does get written and it contains 100 entries.

```
mfind --version
5.2.1
```

**Comment by davepacheco** [comment]
I think there must be a typo in your example.  Was it:

    mfind ~~/stor/stats_data | head -n 100 > test-inputs.txt
